# Copyright 2017, Pablo Ridolfi
# All rights reserved.
#
# This file is part of Workspace.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from this
#    software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

dsp_PATH := modules/dsp

dsp_INC_FOLDERS := $(dsp_PATH)/inc

dsp_SRC_FILES := $(wildcard $(dsp_PATH)/src/*.c) \
                 $(wildcard $(dsp_PATH)/src/dspcode/BasicMathFunctions/*.c) \
                 $(wildcard $(dsp_PATH)/src/dspcode/CommonTables/*.c) \
                 $(wildcard $(dsp_PATH)/src/dspcode/ComplexMathFunctions/*.c) \
                 $(wildcard $(dsp_PATH)/src/dspcode/ControllerFunctions/*.c) \
                 $(wildcard $(dsp_PATH)/src/dspcode/FastMathFunctions/*.c) \
                 $(wildcard $(dsp_PATH)/src/dspcode/FilteringFunctions/*.c) \
                 $(wildcard $(dsp_PATH)/src/dspcode/MatrixFunctions/*.c) \
                 $(wildcard $(dsp_PATH)/src/dspcode/StatisticsFunctions/*.c) \
                 $(wildcard $(dsp_PATH)/src/dspcode/SupportFunctions/*.c) \
                 $(wildcard $(dsp_PATH)/src/dspcode/TransformFunctions/*.c)

dsp_SRC_FOLDERS :=  $(dsp_PATH)/src \
                    $(dsp_PATH)/src/dspcode/BasicMathFunctions \
                    $(dsp_PATH)/src/dspcode/CommonTables \
                    $(dsp_PATH)/src/dspcode/ComplexMathFunctions \
                    $(dsp_PATH)/src/dspcode/ControllerFunctions \
                    $(dsp_PATH)/src/dspcode/FastMathFunctions \
                    $(dsp_PATH)/src/dspcode/FilteringFunctions \
                    $(dsp_PATH)/src/dspcode/MatrixFunctions \
                    $(dsp_PATH)/src/dspcode/StatisticsFunctions \
                    $(dsp_PATH)/src/dspcode/SupportFunctions \
                    $(dsp_PATH)/src/dspcode/TransformFunctions
